apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: bitcoin-trading-system-api:latest # Replace with your image if you build it
          env:
            - name: LOG_LEVEL
              value: "INFO"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /app/logs
              name: api-logs
      volumes:
        - name: api-logs
          emptyDir: {}
      dependsOn:
        - ml-pipeline
        - redis
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: api
  type: ClusterIP
