name: Deploy to Kubernetes

on: 
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: bitcoin-trading-system

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker images
        run: |
          DOCKER_BUILDKIT=1 docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-data-collector:latest -f src/data_collector/Dockerfile .
          DOCKER_BUILDKIT=1 docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-feature-engineering:latest -f src/feature_engineering/Dockerfile .
          DOCKER_BUILDKIT=1 docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-ml-pipeline:latest -f src/ml_pipeline/Dockerfile .
          DOCKER_BUILDKIT=1 docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-trading-bot:latest -f src/trading_bot/Dockerfile .
          DOCKER_BUILDKIT=1 docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-api:latest -f src/api/Dockerfile .
          DOCKER_BUILDKIT=1 docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-mt5-server:latest -f mt5_rpc_server/Dockerfile .

          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-data-collector:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-feature-engineering:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-ml-pipeline:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-trading-bot:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-api:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-mt5-server:latest

      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/database/
          kubectl apply -f k8s/message-queue/
          kubectl apply -f k8s/ml-infra/
          kubectl apply -f k8s/data-collector/
          kubectl apply -f k8s/feature-engineering/
          kubectl apply -f k8s/ml-pipeline/
          kubectl apply -f k8s/trading-bot/
          kubectl apply -f k8s/api/
          kubectl apply -f k8s/mt5-server/
          kubectl apply -f k8s/monitoring/
